# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probes', '0002_auto_20160106_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('primary_site', models.CharField(max_length=50)),
                ('primary_hist', models.CharField(max_length=50)),
            ],
        ),
    ]
