# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('probes', '0003_cellline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=50)),
                ('cell_line_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcell_line_id', to='probes.CellLine')),
                ('platform_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fplatform_id', to='probes.Platform')),
            ],
        ),
        migrations.AddField(
            model_name='probeid',
            name='platform',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='fplatform', to='probes.Platform'),
        ),
    ]
