# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('probes', '0004_auto_20160119_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('data_path', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='dataset_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='fdataset_id', to='probes.Dataset'),
        ),
    ]
