# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probes', '0005_auto_20160216_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='probeid',
            name='offset',
            field=models.IntegerField(default=0),
        ),
    ]
