# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probes', '0006_probeid_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='offset',
            field=models.IntegerField(default=0),
        ),
    ]
