# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-26 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('probes', '0008_auto_20160512_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinical_sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('filename', models.CharField(max_length=50)),
                ('offset', models.IntegerField(default=0)),
                ('age', models.CharField(default='UNKNOWN', max_length=10)),
                ('gender', models.CharField(default='UNKNOWN', max_length=10)),
                ('ethnic', models.CharField(default='UNKNOWN', max_length=20)),
                ('grade', models.CharField(max_length=10)),
                ('stage', models.CharField(max_length=10)),
                ('primary_site', models.CharField(max_length=50)),
                ('primary_hist', models.CharField(max_length=80)),
                ('stageT', models.CharField(default='UNKNOWN', max_length=10)),
                ('stageN', models.CharField(default='UNKNOWN', max_length=10)),
                ('stageM', models.CharField(default='UNKNOWN', max_length=10)),
                ('metastatic', models.BooleanField(default=False)),
                ('dataset_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='clinic_dataset_id', to='probes.Dataset')),
                ('platform_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinc_platform_id', to='probes.Platform')),
            ],
        ),
    ]
