# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-27 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probes', '0010_clinical_dataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinical_sample',
            name='primary_hist',
            field=models.CharField(max_length=100),
        ),
    ]
