# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-27 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('probes', '0011_auto_20161028_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinical_sample',
            name='dataset_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='clinic_dataset_id', to='probes.Clinical_Dataset'),
        ),
    ]
