# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-04 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('probes', '0012_auto_20161028_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='', max_length=20)),
                ('offset', models.IntegerField(default=0)),
                ('platform', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='fplat', to='probes.Platform')),
            ],
        ),
        migrations.CreateModel(
            name='Stand_Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
            ],
        ),
    ]
