# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-05 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('probes', '0013_gene_stand_gene'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stand_Gene',
        ),
    ]
