# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-09 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('probes', '0015_auto_20171009_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cellline',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='cellline',
            name='organ',
        ),
    ]
