# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-16 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probes', '0016_auto_20171009_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinical_sample',
            name='metastatic',
            field=models.NullBooleanField(default=None),
        ),
    ]
