# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-16 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probes', '0017_auto_20171016_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinical_sample',
            name='metastatic',
            field=models.CharField(default='NA', max_length=5),
        ),
    ]
